### PR TITLE
Add latest ce logos

### PR DESCRIPTION
**Pull request by snim2**
When we merged [this PR to the website](https://github.com/dxw/website/pull/103) we forgot to do the same thing here. This PR corrects that.

This PR:

* Removes a link to the old Whippet Server repo which is now archived and not in development.
* Removes `normalize` which Grunt couldn't find after `yarn grunt install` (??)
* Replaces the old CE mark with the new logos and adjusts the footer styling

### Before

advisories dxw com_

### After

localhost_

### CODE REVIEW

**Comment by snim2** [comment]
@matthewpassmore I'm not sure what happened with `normalize` there, but I'm wondering whether we should do [something like this](https://github.com/dxw/website/pull/107) before merging into production.

**Comment by snim2** [comment]
Looking at this again, the underlines on those images need to go

**Comment by snim2** [comment]
This could do with some squashing before merge

**Review by matthewpassmore — APPROVED** [review]
Looks good to me 👍

**Comment by matthewpassmore** [comment]
> @matthewpassmore I'm not sure what happened with `normalize` there, but I'm wondering whether we should do [something like this](https://github.com/dxw/website/pull/107) before merging into production.

Seems sensible, and something that we should apply to WIP projects, also.

**Pull request merged**
